server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

spring:
  cloud:
    config:
      enabled: false

---

spring:
  profile: cloud

eureka:
  client:
    serviceUrl: 
      defaultZone: ${EUREKA_HOST_URL}